apiVersion: v1
kind: Service
metadata:
  name: predict-api
  namespace: shehzad
  labels:
    app: predict-api
spec:
  selector:
    name: predict-api
  ports:
    - name: predict-api
      port: 8000
      targetPort: predict-api
